name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: GitHub Action for SwiftLint with --strict
      uses: norio-nomura/action-swiftlint@9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684 # 3.2.1
      with:
        args: --strict

  tests:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v7

    - name: Run Xcode tests
      run: xcodebuild
        -skipPackagePluginValidation
        -skipMacroValidation
        -project dmenu-mac.xcodeproj
        -scheme dmenu-mac
        -configuration Debug
        test

  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v7

    - name: Build
      run: xcodebuild
        -skipPackagePluginValidation
        -skipMacroValidation
        -scheme dmenu-mac
        -archivePath dmenu-mac.xcarchive archive

    - name: Package
      run: xcodebuild
        -exportArchive
        -archivePath dmenu-mac.xcarchive
        -exportOptionsPlist mac-application-archive.plist
        -exportPath .

    - name: Compress
      run: zip -r dmenu-mac.zip dmenu-mac.app

    - uses: actions/upload-artifact@v7
      with:
        name: dmenu-mac.zip
        path: dmenu-mac.zip
